pc1[0]=A
pc2[0]=B
pc3[0]=C
pc4[0]=D

switch1[0]=A
switch1[1]=B
switch1[2]=T
switch1[image]="kathara/sdn"

switch2[0]=C
switch2[1]=D
switch2[2]=T
switch2[image]="kathara/sdn"


wireshark[0]=T
wireshark[bridged]=true
wireshark[port]="3000:3000/tcp"
wireshark[image]="lscr.io/linuxserver/wireshark:latest"

